
volumes:
  hm_pg_db_vol: {}


services:
  web:
    build: .
    image: hm_web_image
    container_name: hm_web_image
    # To Do: get auto code updating to docker working
    # volumes:
    #   - .:/code
    ports:
      - 8000:8000
    depends_on:
      - pg_db
    env_file: ".env"
    environment:

      POSTGRES_HOST: pg_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

      DATABASE_HOST: pg_db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

    platform: linux/x86_64
    command: sh -c "python manage.py makemigrations &&
        python manage.py migrate &&
        sass static/scss:static/css &&
        python3 manage.py collectstatic --noinput &&
        python3 manage.py runserver 0.0.0.0:8000"


  pg_db:
    image: postgres:16-alpine
    volumes:
      - hm_pg_db_vol:/var/lib/postgresql/data
    restart: unless-stopped
    environment:

      POSTGRES_HOST: pg_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
